[workspace]
name = "g1sim"
version = "0.1.0"
description = "Specialized GPU simulator for Unitree G1 RL locomotion"
authors = ["Thomas"]
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = ">=3.11"
numpy = "*"
mujoco = ">=3.9"
gxx_win-64 = "*"
make = "*"
cuda-nvcc = ">=13.3.33,<14"
cuda-cudart-dev = ">=13.3.29,<14"
clang = ">=22.1.7,<23"
